[package]
name = "rustbik"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
three-d = { version = "0.17.0", default-features = false }
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["WebGl2RenderingContext", "HtmlCanvasElement"] }
